/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homerparser;

import org.junit.jupiter.api.Test;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.stream.Stream;

class LibraryTest {
    @Test void examineTestCase() throws URISyntaxException {
        Library lib = new Library();
    	
    	String json = loadTestFile();
    	lib.parse(json);
    }
    
    @Test void testDownloadJSON() throws InterruptedException {
    	Library lib = new Library();
    	String homerPassword = System.getenv("HOMER_PASSWORD");
    	String result = lib.downloadHomerJSON("Bawat",homerPassword,"https://homer.open-lab.com/?project_uid=PRJ-a5731f74-35c4-4c3a-a7b1-1678665632429", 4000l);
    	assertTrue(result != null && !result.isEmpty());
    }
    
    public String loadTestFile() throws URISyntaxException {
    	StringBuilder strb = new StringBuilder();
    	URI uri = LibraryTest.class.getClassLoader().getResource("testCase.json").toURI();
		try (Stream<String> stream = Files.lines(Paths.get(uri));) {

			stream.forEach(strb::append);

		} catch (IOException e) {
			e.printStackTrace();
		}
		return strb.toString();
    }
}
