/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package homerparser;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import io.github.bonigarcia.wdm.WebDriverManager;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

	public void parse(String json) {
		Gson gson = new Gson();
		
		JsonObject jsonObject = JsonParser.parseString(json).getAsJsonObject();
		
    	JsonArray flows = jsonObject.get("_flows").getAsJsonArray();
    	JsonArray nodes = flows.get(0).getAsJsonObject().get("_nodes").getAsJsonArray();
    	List<HomerNode> homerNodes = new ArrayList<HomerNode>(); for(JsonElement node : nodes.asList()) homerNodes.add(gson.fromJson(node, HomerNode.class));
    	
    	HomerNode startNode = homerNodes.stream().filter(node -> node.isStartNode()).findAny().orElse(null);
    	

		
		HomerNode currentNode = startNode;
    	for(int i = 0; i < 4; i++) {
    		System.out.println(currentNode.toString());
    		currentNode = currentNode.getNextNode();
    	}
	}
	
	public String downloadHomerJSON(String username, String password, String projectURL, long timeout) throws InterruptedException {
		String loginUrl = "https://homer.open-lab.com/login";
		String jsToRun = "return JSON.stringify(Homer.project)";
		
		WebDriverManager.chromedriver().setup();
		
		ChromeOptions chromeOptions = new ChromeOptions();
		chromeOptions.addArguments("--disable-extensions");
		chromeOptions.addArguments("--disable-gpu");
		chromeOptions.addArguments("--no-sandbox");
		chromeOptions.addArguments("--headless");
		chromeOptions.addArguments("--log-level=3");
		chromeOptions.addArguments("--silent");
		System.setProperty("webdriver.chrome.silentOutput", "true");
		System.setProperty("webdriver.http.factory", "apache");
		WebDriver driver = new ChromeDriver(chromeOptions);
		
		driver.get(loginUrl);
		driver.manage().timeouts().implicitlyWait(4, TimeUnit.SECONDS);
		driver.findElement(By.id("user_name")).sendKeys(username);
		driver.findElement(By.id("user_pwd")).sendKeys(password);
		driver.findElement(By.cssSelector("button.main[type='submit']")).click();
		Thread.sleep(timeout);
		driver.get(projectURL);
		Thread.sleep(timeout);
		
		String result = (String) ((JavascriptExecutor) driver).executeScript(jsToRun);
		
		driver.quit();
		
		return result;
	}
}
